"""Lifecycle events and hooks for observing bumblehive agent runs."""

from .events import (
    FINAL_RESULT,
    ITERATION_FINISHED,
    ITERATION_STARTED,
    MODEL_REQUEST_STARTED,
    MODEL_RESPONSE_FINISHED,
    MODEL_STREAM_CONTENT_DELTA,
    MODEL_STREAM_REASONING_DELTA,
    MODEL_STREAM_RECOVERED,
    MODEL_STREAM_TOOL_CALL_DELTA,
    RUN_ERROR,
    RUN_FINISHED,
    RUN_STARTED,
    TOOL_CALL_FINISHED,
    TOOL_CALL_STARTED,
    TOOL_CALLS_FINISHED,
    TOOL_CALLS_STARTED,
    TURN_CONTEXT_BUILT,
    TURN_ERROR,
    TURN_FINISHED,
    TURN_STARTED,
    AgentEvent,
    make_event,
    new_run_id,
)
from .emitter import EventEmitter
from .hooks import (
    AgentHook,
    CallbackHook,
    CompositeHook,
    EventCallback,
    HookInput,
    NoopHook,
    normalize_hooks,
)
from .payloads import (
    error_payload,
    tool_call_payload,
    tool_result_payload,
)
from .recording import EventRecorder
from .streaming import AsyncEventStream, AsyncEventStreamHook

__all__ = [
    "AgentEvent",
    "AgentHook",
    "AsyncEventStream",
    "AsyncEventStreamHook",
    "CallbackHook",
    "CompositeHook",
    "EventCallback",
    "EventEmitter",
    "EventRecorder",
    "FINAL_RESULT",
    "HookInput",
    "ITERATION_FINISHED",
    "ITERATION_STARTED",
    "MODEL_REQUEST_STARTED",
    "MODEL_RESPONSE_FINISHED",
    "MODEL_STREAM_CONTENT_DELTA",
    "MODEL_STREAM_REASONING_DELTA",
    "MODEL_STREAM_RECOVERED",
    "MODEL_STREAM_TOOL_CALL_DELTA",
    "NoopHook",
    "RUN_ERROR",
    "RUN_FINISHED",
    "RUN_STARTED",
    "TOOL_CALL_FINISHED",
    "TOOL_CALL_STARTED",
    "TOOL_CALLS_FINISHED",
    "TOOL_CALLS_STARTED",
    "TURN_CONTEXT_BUILT",
    "TURN_ERROR",
    "TURN_FINISHED",
    "TURN_STARTED",
    "error_payload",
    "make_event",
    "new_run_id",
    "normalize_hooks",
    "tool_call_payload",
    "tool_result_payload",
]
