[package]
name = "bumblehive-desktop"
version = "0.1.0"
description = "BumbleHive desktop application"
authors = ["BumbleHive"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
tauri-plugin-dialog = "2.6.0"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.4"
objc2-app-kit = { version = "0.3.2", default-features = false, features = ["NSColor", "NSGraphics", "NSResponder", "NSView", "objc2-core-foundation", "objc2-core-graphics", "objc2-core-image", "objc2-quartz-core"] }
objc2-core-image = { version = "0.3.2", default-features = false, features = ["CIFilter", "CIFilterBuiltins"] }
objc2-quartz-core = { version = "0.3.2", default-features = false, features = ["CALayer", "objc2-core-foundation", "objc2-core-graphics"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
